### ISSUE TITLE
Add guide to change theme colors

### ISSUE THREAD

**Issue by kirontoo** [kirontoo/astro-theme-cody#2]

**Comment by liuyinz** [comment]
Thansk for you great package. the markdown code block theme do not change with dark/light, is it a bug ?

**Comment by kirontoo** [comment]
@liuyinz this might be a bug with the shiki config or astro. I'm not sure.

Try configuring the syntax highlighting using the astro docs: https://docs.astro.build/en/guides/markdown-content/#syntax-highlighting

Or try the [astro GitHub issues](https://github.com/withastro/astro/issues) or [shiki GitHub issues](https://github.com/shikijs/shiki/issues).

Also next time if you have an issue, please create a new issue instead of commenting on an existing one.
