### ISSUE TITLE
Change font size for blog and project posts

### ISSUE THREAD

**Issue by mediodiablo** [kirontoo/astro-theme-cody#32]
In the global.css file, html body section, I changed the font size from "text-sm" to "text-lg".
This updates the font size in all pages except for blog and project posts.
How can we apply the changes to posts?
Thank you.

**Comment by kirontoo** [comment]
Within `src/layouts/BlogPost.astro` and `src/layouts/Project.astro` find the `prose-sm` CSS class and change it to `prose-lg`.

**Comment by staz0t** [comment]
Hi - when I increase the font size using the methods mentioned above, some formatting goes whacky. Mainly, the list of posts on the homepage. How can I fix this?

![Image](https://github.com/user-attachments/assets/f6765c37-ce68-46ab-8b17-1011d948c9e3)
![Image](https://github.com/user-attachments/assets/e2345b7c-e2fa-40aa-9cf0-9c971b90b452)
